import importlib.util
from pathlib import Path
import unittest
try:
    import torch
    from transformers import GPTNeoXConfig, GPTNeoXForCausalLM
except ImportError:
    torch = None

path=Path(__file__).resolve().parents[1]/'examples/autogenerated/lora-learning-dynamics/run.py'
if torch is not None:
    spec=importlib.util.spec_from_file_location('learning_dynamics',path)
    experiment=importlib.util.module_from_spec(spec)
    spec.loader.exec_module(experiment)

@unittest.skipIf(torch is None, 'requires pinned CPU torch/transformers; exercised in Pythia workflow')
class LearningDynamicsTests(unittest.TestCase):
    def test_three_terms_reconstruct_nonzero_two_factor_update(self):
        torch.manual_seed(8)
        a,b=torch.randn(2,3,dtype=torch.float64),torch.randn(4,2,dtype=torch.float64)
        da,db=torch.randn_like(a),torch.randn_like(b)
        terms=experiment.decompose(a,b,da,db,0.5)
        actual=0.5*((b+db)@(a+da)-b@a)
        torch.testing.assert_close(actual,sum(terms),rtol=1e-13,atol=1e-13)
        self.assertGreater(terms[2].norm().item(),0)

    def test_jvp_matches_independent_finite_difference_on_tiny_neox(self):
        torch.manual_seed(9)
        torch.set_default_dtype(torch.float64)
        self.addCleanup(torch.set_default_dtype,torch.float32)
        model=GPTNeoXForCausalLM(GPTNeoXConfig(vocab_size=17,hidden_size=8,
              intermediate_size=16,num_hidden_layers=2,num_attention_heads=2,
              rotary_pct=0.5,attention_dropout=0,hidden_dropout=0,
              _attn_implementation='eager')).double().eval()
        target='gpt_neox.layers.0.attention.query_key_value'
        adapter=experiment.attach_lora(model,target,seed=2)
        a=adapter.a.detach().clone()
        b=torch.randn_like(adapter.b)*0.01
        da,db=torch.randn_like(a)*0.001,torch.randn_like(b)*0.001
        row,_=experiment.compare_probe(model,adapter,target,torch.tensor([[1,2,3,4]]),1,a,b,da,db)
        self.assertLess(row['jvp_fd_error_l2'],1e-7)
        self.assertGreater(row['logit_actual_l2'],0)
        self.assertGreater(row['logit_residual_l2'],0)

if __name__=='__main__':
    unittest.main()
