import copy
import importlib.util
from pathlib import Path
import unittest

path=Path(__file__).resolve().parents[1]/'examples/autogenerated/pythia-bme-margin/dense.py'
spec=importlib.util.spec_from_file_location('dense_bme',path)
dense=importlib.util.module_from_spec(spec)
spec.loader.exec_module(dense)

class DenseComparisonTests(unittest.TestCase):
    def receipt(self):
        return {'pairs':[{'prompt':p,'pair':i,'margin':0.1} for p in
                ('bme_original','bme_heldout','unrelated_school_question') for i in (1,2,3)],
                'neutral_mean_logp':[-2.0,-3.0,-4.0]}

    def test_independent_tensor_behavior_and_pair_flags(self):
        reference=self.receipt()
        self.assertTrue(dense.anchor_comparison({'relative_l2':0},reference,reference)['within_comparison_tolerances'])
        changed=copy.deepcopy(reference)
        changed['pairs'][2]['margin']+=0.021
        self.assertFalse(dense.anchor_comparison({'relative_l2':0},changed,reference)['within_comparison_tolerances'])
        changed=copy.deepcopy(reference)
        changed['neutral_mean_logp'][1]-=0.021
        self.assertFalse(dense.anchor_comparison({'relative_l2':0},changed,reference)['within_comparison_tolerances'])
        self.assertFalse(dense.anchor_comparison({'relative_l2':0.0011},reference,reference)['within_comparison_tolerances'])

    def test_incomplete_misaligned_or_nonfinite_scores_refuse(self):
        reference=self.receipt()
        for defect in ('missing','coordinate','nan'):
            changed=copy.deepcopy(reference)
            if defect=='missing': changed['pairs'].pop()
            if defect=='coordinate': changed['pairs'][1]['pair']=3
            if defect=='nan': changed['neutral_mean_logp'][1]=float('nan')
            with self.assertRaises(ValueError):
                dense.anchor_comparison({'relative_l2':0},changed,reference)
